[package]
name = "too_big_to_exploit_webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.0"
axum = "0.6.11"
base64 = "0.21.0"
once_cell = "1.17.1"
rand = "0.8.5"
rust_decimal = { version = "1.29.1", features = ["db-tokio-postgres"] }
serde = { version = "1.0.158", features = ["derive"] }
tera = "1.18.1"
tokio = { version = "1.26.0", features = ["full"] }
tokio-postgres = "0.7.8"
tower-cookies = "0.9.0"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
