[package]
name = "too_big_to_exploit_webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.11"
once_cell = "1.17.1"
rust_decimal = { version = "1.29.1", features = ["db-tokio-postgres"] }
serde = { version = "1.0.158", features = ["derive"] }
tera = "1.18.1"
tokio = { version = "1.26.0", features = ["full"] }
tokio-postgres = "0.7.8"
tower-cookies = "0.9.0"
